version: '3.8'

services:
  nginx:
    image: "${NGINX_IMAGE}"
    container_name: api-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - PORT=${PORT}
    ports:
      - 80:80
      - 443:443
    command: >
            /bin/sh -c
            "envsubst '
            $${SERVER_NAME}
            $${PORT}
            '< /etc/nginx/conf.d/default.conf.template
            > /etc/nginx/conf.d/nginx.conf
            && nginx -g 'daemon off;'"
  certbot:
    image: certbot/certbot
    container_name: api-certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email ${CERTIFICATE_EMAIL} -d ${SERVER_NAME} --agree-tos