version: '3.8'

services:
  nestjs:
    image: "${NESTJS_IMAGE}"
    container_name: api-nestjs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres
    container_name: api-postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: api-redis
    restart: always
    ports:
      - 6379:6379
    env_file:
      - .env
  nginx:
    image: "${NGINX_IMAGE}"
    container_name: api-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    environment:
      - SERVER_NAME=${SERVER_NAME}
    command: >
            /bin/sh -c
            "envsubst '
            $${SERVER_NAME}
            '< /etc/nginx/nginx.conf.template
            > /etc/nginx/nginx.conf
            && nginx -g 'daemon off;'"
    depends_on:
      - postgres
      - redis
      - nestjs
volumes:
  postgres:
    name: potedev-db