version: '3.8'
services:
  postgres:
    image: postgres
    container_name: api-postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: potedev-dev-db

networks:
  default:
    external:
      name: nginx-proxy